import {
  ServiceInvoice,
  PartsSale,
  OperatingExpense,
  InventoryPurchase,
  StaffMember,
  JobTask,
} from "./types";

export const initialStaff: StaffMember[] = [
  {
    id: "st_1",
    name: "Jean Dupont",
    role: "Lead Mechanic",
    phone: "+33 6 12 34 56 78",
    hourlyRate: 45,
    status: "Active",
  },
  {
    id: "st_2",
    name: "Ahmed Mansour",
    role: "Engine Specialist",
    phone: "+971 50 123 4567",
    hourlyRate: 50,
    status: "Active",
  },
  {
    id: "st_3",
    name: "Sarah Miller",
    role: "Diagnostics Expert",
    phone: "+1 555 019 2834",
    hourlyRate: 40,
    status: "Active",
  },
  {
    id: "st_4",
    name: "Marc Laurent",
    role: "Suspension Technician",
    phone: "+33 6 98 76 54 32",
    hourlyRate: 35,
    status: "On Leave",
  },
];

export const initialInvoices: ServiceInvoice[] = [
  {
    id: "inv_1",
    customerName: "Alice Smith",
    customerPhone: "+1 555 014 9922",
    vehicleModel: "BMW 320i (2018)",
    licensePlate: "NY-789-AB",
    description: "Front brake pads and brake rotor replacement",
    mechanicId: "st_3",
    partsCost: 120,
    laborCost: 150,
    totalAmount: 270,
    date: "2026-06-20",
    paymentStatus: "Paid",
  },
  {
    id: "inv_2",
    customerName: "Pierre Martin",
    customerPhone: "+33 6 11 22 33 44",
    vehicleModel: "Peugeot 3008 (2020)",
    licensePlate: "AA-123-BB",
    description: "Full synthetic oil service and oil filter replacement",
    mechanicId: "st_1",
    partsCost: 45,
    laborCost: 60,
    totalAmount: 105,
    date: "2026-06-22",
    paymentStatus: "Paid",
  },
  {
    id: "inv_3",
    customerName: "Fatma Al-Sayed",
    customerPhone: "+971 55 987 6543",
    vehicleModel: "Toyota Camry (2019)",
    licensePlate: "DXB-9988",
    description: "Check engine light diagnostics and oxygen sensor swap",
    mechanicId: "st_2",
    partsCost: 85,
    laborCost: 100,
    totalAmount: 185,
    date: "2026-06-24",
    paymentStatus: "Partial",
  },
];

export const initialPartsSales: PartsSale[] = [
  {
    id: "sale_1",
    partName: "Brembo Brake Pads (Front)",
    customerName: "Bob Johnson",
    quantity: 2,
    unitPrice: 55,
    totalAmount: 110,
    date: "2026-06-18",
  },
  {
    id: "sale_2",
    partName: "Castrol Edge 5W30 (1L)",
    customerName: "George Brown",
    quantity: 4,
    unitPrice: 18,
    totalAmount: 72,
    date: "2026-06-21",
  },
];

export const initialExpenses: OperatingExpense[] = [
  {
    id: "exp_1",
    category: "Rent",
    description: "Workshop Facility Monthly Lease",
    amount: 2500,
    date: "2026-06-01",
  },
  {
    id: "exp_2",
    category: "Electricity",
    description: "May Electricity Grid Invoice",
    amount: 320,
    date: "2026-06-12",
  },
  {
    id: "exp_3",
    category: "Water",
    description: "Municipal Water Utility Bill",
    amount: 65,
    date: "2026-06-15",
  },
  {
    id: "exp_4",
    category: "Internet",
    description: "High-Speed Fiber Business Plan",
    amount: 110,
    date: "2026-06-05",
  },
  {
    id: "exp_5",
    category: "Maintenance",
    description: "Two-Post Hydraulic Lift Inspection and Oil Change",
    amount: 450,
    date: "2026-06-18",
  },
];

export const initialPurchases: InventoryPurchase[] = [
  {
    id: "pur_1",
    itemName: "Premium Brake Calipers",
    supplier: "AutoParts Distributor Ltd",
    quantity: 10,
    unitCost: 75,
    totalCost: 750,
    date: "2026-06-10",
    status: "Received",
  },
  {
    id: "pur_2",
    itemName: "Synthetic Oil 5W30 (60L Drum)",
    supplier: "Lubricants Global Inc",
    quantity: 3,
    unitCost: 180,
    totalCost: 540,
    date: "2026-06-14",
    status: "Received",
  },
  {
    id: "pur_3",
    itemName: "High-Flow Intake Air Filters",
    supplier: "Global Filters Corp",
    quantity: 25,
    unitCost: 12,
    totalCost: 300,
    date: "2026-06-23",
    status: "Pending",
  },
];

export const initialJobs: JobTask[] = [
  {
    id: "job_1",
    description: "Replace steering rack tie-rod ends and execute wheel alignment",
    vehicleDetails: "Audi A4 (2017)",
    assignedStaffId: "st_1",
    status: "In Progress",
    estimatedHours: 3.5,
    date: "2026-06-25",
  },
  {
    id: "job_2",
    description: "A/C refrigerant pressure check and system recharge",
    vehicleDetails: "Ford Mustang GT (2015)",
    assignedStaffId: "st_2",
    status: "Pending",
    estimatedHours: 1.5,
    date: "2026-06-25",
  },
  {
    id: "job_3",
    description: "Rear shocks and suspension struts overhaul",
    vehicleDetails: "Volkswagen Golf GTI (2019)",
    assignedStaffId: "st_3",
    status: "Completed",
    estimatedHours: 4.0,
    date: "2026-06-24",
  },
];
